apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- common/namespaces.yaml
- common/source.yaml
- sops.yaml
- helm/argo-rollouts.yaml
- helm/prometheus.yaml
- helm/nats.yaml
- helm/releases.yaml
- deployments.yaml