apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: todo-secrets
  namespace: flux-system
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: app-repo
  path: ./apps/project
  prune: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age