apiVersion: v1
kind: Namespace
metadata:
  name: todo-namespace

---

apiVersion: v1
kind: Namespace
metadata:
  name: prometheus
  
---

apiVersion: v1
kind: Namespace
metadata:
  name: argo-rollouts