apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: todo-backend
  namespace: flux-system
spec:
  targetNamespace: todo-namespace
  sourceRef:
    kind: GitRepository
    name: app-repo
  interval: 10m
  path: ./apps/project
  prune: true
  validation: client

---

apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: todo-ui
  namespace: flux-system
spec:
  targetNamespace: todo-namespace
  sourceRef:
    kind: GitRepository
    name: app-repo
  interval: 10m
  path: ./apps/project_front
  prune: true
  validation: client

---

apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: broadcaster
  namespace: flux-system
spec:
  targetNamespace: todo-namespace
  sourceRef:
    kind: GitRepository
    name: app-repo
  interval: 10m
  path: ./apps/broadcaster
  prune: true
  validation: client