apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: app-repo
  namespace: flux-system
spec:
  interval: 10m
  url: https://github.com/sokkanen/devopswithkubernetes
  ref:
    branch: main